import type { ActivityCategory, CreateActivityInput } from '../src/domain/types';
import type { QiahaoDatabase } from './db';

const categories = new Set<ActivityCategory>(['饭搭子', '咖啡', '运动', '徒步', '看展', '桌游']);
type User = { id: string; name: string; avatar: string; verified: number; bio: string };
function toUser(row: User) { return { id: row.id, name: row.name, avatar: row.avatar, verified: Boolean(row.verified), bio: row.bio }; }
function toActivity(db: QiahaoDatabase, row: any, userId: string) {
  const participants = db.raw.prepare(`SELECT u.id,u.name,u.avatar,u.verified,u.bio FROM activity_members m JOIN users u ON u.id=m.user_id WHERE m.activity_id=? ORDER BY m.created_at`).all(row.id) as User[];
  const saved = Boolean(db.raw.prepare('SELECT 1 FROM favorites WHERE user_id=? AND activity_id=?').get(userId, row.id));
  const joined = Boolean(db.raw.prepare('SELECT 1 FROM activity_members WHERE user_id=? AND activity_id=?').get(userId, row.id));
  return { id: row.id, title: row.title, category: row.category, image: row.image, dateLabel: row.date_label, time: row.time, location: row.location, distance: row.distance, description: row.description, host: toUser(row.host), participants: participants.map(toUser), capacity: row.capacity, price: row.price, featured: Boolean(row.featured), note: row.note, saved, joined };
}
function withHost(row: any) { return { ...row, host: { id: row.host_user_id, name: row.host_name, avatar: row.host_avatar, verified: row.host_verified, bio: row.host_bio } }; }
export function listActivities(db: QiahaoDatabase, userId: string) { const rows = db.raw.prepare(`SELECT a.*, u.id AS host_user_id,u.name AS host_name,u.avatar AS host_avatar,u.verified AS host_verified,u.bio AS host_bio FROM activities a JOIN users u ON u.id=a.host_id ORDER BY a.featured DESC, a.created_at DESC`).all() as any[]; return rows.map((row) => toActivity(db, withHost(row), userId)); }
export function getActivity(db: QiahaoDatabase, userId: string, id: string) { const row = db.raw.prepare(`SELECT a.*, u.id AS host_user_id,u.name AS host_name,u.avatar AS host_avatar,u.verified AS host_verified,u.bio AS host_bio FROM activities a JOIN users u ON u.id=a.host_id WHERE a.id=?`).get(id) as any; return row ? toActivity(db, withHost(row), userId) : null; }
export function validateActivity(input: Partial<CreateActivityInput>) { if (!input.title?.trim() || !input.description?.trim() || !input.location?.trim() || !input.dateLabel?.trim() || !input.time?.trim()) return '请完整填写活动信息'; if (!categories.has(input.category as ActivityCategory)) return '活动类型无效'; if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(input.time)) return '时间格式无效'; if (!Number.isInteger(input.capacity) || input.capacity! < 2 || input.capacity! > 50) return '人数需在 2 至 50 人之间'; if (!Number.isInteger(input.price) || input.price! < 0) return '费用不能为负数'; return null; }
export function createActivity(db: QiahaoDatabase, userId: string, input: CreateActivityInput) { const id = `created-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; const images: Record<ActivityCategory, string> = { '饭搭子': '/assets/food.jpg', '咖啡': '/assets/coffee.jpg', '运动': '/assets/sport.jpg', '徒步': '/assets/hike.jpg', '看展': '/assets/art.jpg', '桌游': '/assets/board.jpg' }; const now = new Date().toISOString(); db.raw.prepare(`INSERT INTO activities (id,host_id,title,category,image,date_label,time,location,distance,description,capacity,price,featured,note,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id, userId, input.title.trim(), input.category, images[input.category], input.dateLabel.trim(), input.time, input.location.trim(), '由你发起', input.description.trim(), input.capacity, input.price, 0, '请在活动开始前与参与者确认集合信息。', now); return getActivity(db, userId, id)!; }
