import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import type { QiahaoDatabase } from './db';
const scrypt = promisify(scryptCallback);
export interface AuthenticatedUser { id: string; phone: string; name: string; avatar: string; bio: string; verified: boolean }
export async function hashPassword(password: string): Promise<string> { const salt = randomBytes(16); const key = await scrypt(password, salt, 64) as Buffer; return `scrypt$${salt.toString('hex')}$${key.toString('hex')}`; }
export async function verifyPassword(password: string, stored: string): Promise<boolean> { const [, saltHex, keyHex] = stored.split('$'); if (!saltHex || !keyHex) return false; const actual = await scrypt(password, Buffer.from(saltHex, 'hex'), 64) as Buffer; const expected = Buffer.from(keyHex, 'hex'); return actual.length === expected.length && timingSafeEqual(actual, expected); }
export function tokenHash(token: string): string { return createHash('sha256').update(token).digest('hex'); }
export function createSession(db: QiahaoDatabase, userId: string): string { const token = randomBytes(32).toString('base64url'); const date = new Date(); const expires = new Date(date.getTime() + 30 * 86400000).toISOString(); db.raw.prepare('INSERT INTO sessions (id,user_id,token_hash,expires_at,created_at) VALUES (?,?,?,?,?)').run(randomUUID(), userId, tokenHash(token), expires, date.toISOString()); return token; }
export function authenticateToken(db: QiahaoDatabase, header?: string): AuthenticatedUser | null { const token = header?.startsWith('Bearer ') ? header.slice(7) : ''; if (!token) return null; const row = db.raw.prepare(`SELECT u.id,u.phone,u.name,u.avatar,u.bio,u.verified,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?`).get(tokenHash(token)) as { id: string; phone: string; name: string; avatar: string; bio: string; verified: number; expires_at: string } | undefined; if (!row || Date.parse(row.expires_at) <= Date.now()) return null; return { id: row.id, phone: row.phone, name: row.name, avatar: row.avatar, bio: row.bio, verified: Boolean(row.verified) }; }
