import type { ClubActivity, LifePost, Need } from './types';

export interface QaQuestion {
  title: string;
  options?: string[];
  groups?: Array<{ label: string; options: string[] }>;
  multiple?: boolean;
  text?: boolean;
  voice?: boolean;
  placeholder?: string;
}

export const lightQuestions = [
  { title: '你最近最想解决什么？', options: ['想认识靠谱的人', '想自然一点脱单', '想找能深聊的人', '想扩大线下社交圈', '想理解关系模式', '暂时不确定'] },
  { title: '你更容易接受哪种见面场景？', options: ['少人数饭局', '轻松散步', '主题 deep talk', '共同兴趣活动', '关系工作坊', '小组匹配'] },
  { title: '你最大的出门阻力是什么？', options: ['怕尴尬', '怕人多', '怕太像相亲', '怕聊不起来', '地点太远', '不知道来的人怎样'] },
];

export const qaSets = {
  basic: [
    { title: '你更喜欢哪种规模的活动？', multiple: true, options: ['6人以下私密小局', '10-20人', '20-50人', '50人以上大型派对'] },
    { title: '你能接受单次活动的最长时长是？', options: ['1-2小时', '2-4小时', '半天', '全天'] },
    { title: '参加活动时，你能接受的路程时间是？', options: ['30分钟内', '1小时内', '只要值得，距离不限'] },
    { title: '未来7天，你的可约档期是？', multiple: true, options: ['工作日晚间（周一至周四19:00后）', '周五晚上（开启周末模式）', '周六白天', '周六晚上', '周日白天', '周日晚上', '最近想先线上聊聊，暂不见面'] },
  ],
  extra: [
    { title: '初次见面，怎样开始让你最舒服？', options: ['有主持人/规则，先玩个游戏再聊', '从共同兴趣聊起，不愁没话题', '慢热型，先给点独处空间', '直接来深处话题，不想浪费时间客套'] },
    { title: '在喜欢的人面前，你通常是？', options: ['主动型，喜欢就会靠近', '慢热型，熟了之后话很多', '被动型，需要对方给我信号', '状态型，感觉对了就主动'] },
    { title: '哪句话最接近你的感情观？', options: ['先看感觉，感觉对了什么都可以谈', '三观合拍比心动更重要', '关系是两个人一起修出来的，不存在完美匹配', '爱自己要优先于爱对方'] },
    { title: '你现在在感情上更接近哪种状态？', options: ['单身很久，想认真脱单但不想将就', '有目标类型，但一直没遇到对的', '刚结束一段关系，想先找回自己', '佛系随缘，碰到同频的再说', '母胎单身，需要有人带带'] },
  ],
  advanced: [
    {
      title: '最容易被异性哪种特质吸引？',
      multiple: true,
      groups: [
        { label: '外在', options: ['长相干净舒服', '穿搭有品味', '气质好有辨识度'] },
        { label: '内在', options: ['温柔有耐心，接得住情绪', '幽默有趣，能接梗抛梗', '情绪稳定，不情绪化'] },
        { label: '处理事情的方式', options: ['有主见，不随波逐流', '遇事有解决问题的能力', '有自己热爱的事，很专注'] },
      ],
    },
    { title: '如果和一个人聊得还不错，哪些是阻碍你下一步行动的阻力？', multiple: true, options: ['害怕主动', '不确定对方态度', '生活节奏忙', '担心破坏现有关系', '慢热需要时间', '对线下见面有焦虑'] },
    { title: '亲密关系里，你如何看待边界感与个人空间？哪些事你不愿被干涉？', text: true, voice: true, placeholder: '可以打字，也可以用语音说一段。比如：我需要彼此信任，不希望被干涉消费决定、兴趣爱好、社交方式。' },
  ],
} satisfies Record<'basic' | 'extra' | 'advanced', QaQuestion[]>;

const pics = [
  '/assets/qiahao-social-dinner.png',
  '/assets/qiahao-deep-talk.png',
  '/assets/qiahao-city-walk.png',
  '/assets/qiahao-workshop.png',
  '/assets/qiahao-city-walk.png',
  '/assets/qiahao-deep-talk.png',
];

const defaultBoundary = '不强配对、不公开联系方式、不强制交换微信，任何问题都可以选择不回答。';
const defaultAudience = '多为25-35岁，想认真认识人但排斥强相亲';

export const clubActivities: ClubActivity[] = [
  {
    id: 'club-dinner',
    theme: 'low',
    status: '成熟活动',
    title: '周五轻聊天晚餐局',
    tags: ['低压力', '少人数', '怕尴尬'],
    description: '流程清楚的小桌轻餐，适合第一次低压力见面。',
    image: pics[0],
    date: '周五 · 19:30',
    location: 'KIC / 大学路附近',
    people: '6-8人',
    fee: '¥89',
    needs: ['想认识靠谱的人', '怕尴尬', '少人数', '自然聊天'],
    timeRange: '周五 19:30-21:30',
    audience: defaultAudience,
    pitch: '用清楚流程和少人数桌局，降低第一次见面的尴尬。',
    matchLabel: '高匹配',
    boundary: defaultBoundary,
    flow: [
      { title: '19:30 到场', body: '小CC/主理人轻破冰，不做简历式自我介绍。' },
      { title: '19:45 共桌轻餐', body: '围绕3个低压力话题自然聊天。' },
      { title: '20:35 自由换座', body: '可继续聊，也可加入散步小组。' },
      { title: '21:20 反馈', body: '写下想继续认识谁、还顾虑什么。' },
    ],
  },
  {
    id: 'club-night',
    theme: 'deep',
    status: '预活动',
    title: '深度对谈夜局',
    tags: ['deep talk', '价值观', '不强相亲'],
    description: '围绕三个真实关系问题，先收集感兴趣人数。',
    image: pics[1],
    date: '周五 · 20:00',
    location: '大学路合作空间',
    people: '6人',
    fee: '¥69',
    needs: ['想找能深聊的人', '价值观', '不强相亲'],
    timeRange: '周五 20:00-22:00',
    audience: '喜欢慢聊、愿意分享真实想法的人',
    pitch: '围绕三个真实关系问题，先听彼此，再决定要不要靠近。',
    matchLabel: '深聊向',
    boundary: defaultBoundary,
    flow: [
      { title: '20:00 到场', body: '简单认识，确认今晚的三个问题。' },
      { title: '20:15 深度对谈', body: '分组围绕价值观与关系体验自然聊天。' },
      { title: '21:20 自由交流', body: '可继续聊，也可提前安静离开。' },
      { title: '21:50 收束', body: '写下今晚印象最深的一句话。' },
    ],
  },
  {
    id: 'club-walk',
    theme: 'walk',
    status: '成熟活动',
    title: '我们向月亮走去 · 周五散步局',
    tags: ['散步', '轻社交', '低压力'],
    description: '城市散步，5人成行，走到哪聊到哪。',
    image: pics[2],
    date: '周六 · 19:00',
    location: '江湾体育场出发',
    people: '5人成行',
    fee: '免费',
    needs: ['低压力', '轻社交', '附近'],
    timeRange: '周六 19:00-20:30',
    audience: '想慢慢认识、不喜欢室内局的人',
    pitch: '城市散步，5人成行，走到哪聊到哪。',
    matchLabel: '低压力',
    boundary: '不强制结伴回家，不交换联系方式也可完整参加。',
    flow: [
      { title: '19:00 集合', body: '江湾体育场门口轻破冰，确认路线。' },
      { title: '19:15 边走边聊', body: '两三人一组自然聊天，可随时换位。' },
      { title: '20:10 补给', body: '找地方喝水休息，想继续的人可加一段。' },
      { title: '20:30 散场', body: '各自离开，不强制合影或加微信。' },
    ],
  },
  {
    id: 'club-workshop',
    theme: 'workshop',
    status: '预活动',
    title: '关系说明书工作坊',
    tags: ['关系模式', '工作坊', '慢了解'],
    description: '通过关系说明书练习表达自己的靠近方式。',
    image: pics[3],
    date: '周六 · 14:00',
    location: '大学路',
    people: '10人',
    fee: '¥99',
    needs: ['想理解关系模式', '慢了解', '工作坊'],
    timeRange: '周六 14:00-17:00',
    audience: '对关系有困惑、愿意认真练习表达的人',
    pitch: '用一份关系说明书，练习说出自己的靠近方式。',
    matchLabel: '练习向',
    boundary: defaultBoundary,
    flow: [
      { title: '14:00 开场', body: '说明规则与安全边界，不做公开点名。' },
      { title: '14:20 个人书写', body: '写下自己的关系说明书要点。' },
      { title: '15:10 小组共创', body: '小范围分享，可选择只听不说。' },
      { title: '16:30 收束', body: '带走一张属于自己的说明书。' },
    ],
  },
  {
    id: 'club-lunch',
    theme: 'low',
    status: '成熟活动',
    title: '午间同频小桌',
    tags: ['附近', '午间', '低压力'],
    description: '一小时，一顿饭的时间，认识附近的人。',
    image: pics[0],
    date: '周三 · 12:30',
    location: '静安寺附近',
    people: '4人',
    fee: '¥59',
    needs: ['附近', '午间', '低压力'],
    timeRange: '周三 12:30-13:30',
    audience: '工作日想轻松认识附近人的上班族',
    pitch: '一小时，一顿饭的时间，认识附近的人。',
    matchLabel: '附近',
    boundary: defaultBoundary,
    flow: [
      { title: '12:30 入座', body: '4人小桌，简单自我介绍一句即可。' },
      { title: '12:40 共餐聊天', body: '围绕最近生活与周末计划自然聊。' },
      { title: '13:20 收束', body: '想继续认识的人可自行约定。' },
    ],
  },
  {
    id: 'club-exhibit',
    theme: 'other',
    status: '成熟活动',
    title: '周末看展 + 咖啡',
    tags: ['看展', '轻社交', '文艺'],
    description: '一起看展，看完随便聊聊。',
    image: pics[3],
    date: '周日 · 15:00',
    location: '西岸美术馆',
    people: '6人',
    fee: '¥79',
    needs: ['看展', '文艺', '轻社交'],
    timeRange: '周日 15:00-17:30',
    audience: '喜欢慢节奏、愿意分享感受的人',
    pitch: '一起看展，看完随便聊聊，不需要专业知识。',
    matchLabel: '文艺',
    boundary: defaultBoundary,
    flow: [
      { title: '15:00 集合', body: '展馆入口集合，分发展览动线建议。' },
      { title: '15:15 自由观展', body: '可结伴也可独自看，不强行讲解。' },
      { title: '16:30 咖啡复盘', body: '馆外聊聊最喜欢的一件作品。' },
    ],
  },
  {
    id: 'club-poem',
    theme: 'deep',
    status: '预活动',
    title: '阳台夜话 · 诗集共读',
    tags: ['文艺', '慢聊', '少人数'],
    description: '5人小局，读诗也读自己。',
    image: pics[1],
    date: '周四 · 19:30',
    location: '安福路',
    people: '5人',
    fee: '¥49',
    needs: ['文艺', '慢聊', '少人数'],
    timeRange: '周四 19:30-21:30',
    audience: '喜欢文字、愿意慢聊的人',
    pitch: '5人小局，读诗也读自己。',
    matchLabel: '慢聊',
    boundary: defaultBoundary,
    flow: [
      { title: '19:30 入座', body: '发诗集片段，围坐认识。' },
      { title: '19:50 共读', body: '每人选一段读或听。' },
      { title: '20:40 夜话', body: '从诗句聊到最近的感受。' },
    ],
  },
  {
    id: 'club-ride',
    theme: 'walk',
    status: '预活动',
    title: '滨江骑行轻食局',
    tags: ['户外', '骑行', '轻运动'],
    description: '不比赛，慢慢骑，累了就喝咖啡。',
    image: pics[4],
    date: '周六 · 09:30',
    location: '滨江',
    people: '8人',
    fee: '¥109',
    needs: ['户外', '轻运动', '低压力'],
    timeRange: '周六 09:30-12:00',
    audience: '想户外活动但不想卷配速的人',
    pitch: '不比赛，慢慢骑，累了就喝咖啡。',
    matchLabel: '户外',
    boundary: '自备或租用车辆，量力而行，可随时退出路线。',
    flow: [
      { title: '09:30 集合', body: '确认车辆与安全须知。' },
      { title: '09:50 骑行', body: '滨江慢骑，中途可停拍照。' },
      { title: '11:20 轻食', body: '找地方补给，自由聊天。' },
    ],
  },
];

export const seedNeeds: Need[] = [
  { id: 'd1', author: '林 · 2小时前', subtitle: '正在寻找低压力的认识方式', tags: ['想认识靠谱的人', '少人数'], title: '不想尴尬交换微信，但想认真认识人', copy: '如果有一个中间场域，我会更愿意出来。先轻松认识，不急着定义关系。', image: pics[1], resonance: 72, comments: 38, response: '主理人正在准备低压力小桌局', responseActivityId: 'club-dinner', similar: true },
  { id: 'd2', author: 'Mei · 昨天', subtitle: '想重新感受到关系里的松弛', tags: ['关系困惑', '慢慢了解'], title: '不是不想恋爱，是越来越难进入关系', copy: '希望有一场聊“心动变难”的局，不急着定义关系。', image: pics[4], resonance: 45, comments: 22, response: '关系主题预活动准备中', responseActivityId: 'club-workshop' },
  { id: 'd3', author: '阿南 · 3天前', subtitle: '想找到能认真聊天的同频朋友', tags: ['deep talk', '价值观'], title: '想找能聊价值观的人，而不是只聊工作', copy: '6个人的小型夜谈，可能比一场大活动更适合认真认识。', image: pics[5], resonance: 28, comments: 8, response: '深度对谈预活动收集中', responseActivityId: 'club-night' },
  { id: 'd4', author: '小满 · 6小时前', subtitle: '住同一片，却从没聊过天', tags: ['附近', '周末', '散步'], title: '周末想找同小区附近的人，一起散步遛狗', copy: '住得近，却从没好好说过话。想先从散步开始认识。', image: pics[2], resonance: 33, comments: 12, response: '散步局已有3人感兴趣', responseActivityId: 'club-walk', similar: true },
  { id: 'd5', author: '圆圆 · 昨天', subtitle: '怕尴尬、想慢慢来', tags: ['怕尴尬', '少人数'], title: '第一次见面能不能不交换微信', copy: '先认识，不急着留联系方式，舒服了再交换。', image: pics[1], resonance: 51, comments: 20, response: '低压力小桌局回应中', responseActivityId: 'club-dinner', similar: true },
  { id: 'd6', author: '阿May · 今天', subtitle: '喜欢看展、慢节奏', tags: ['看展', '文艺', '轻社交'], title: '想找人一起看展，然后随便聊聊', copy: '看完展不用硬聊，舒服就好。', image: pics[3], resonance: 17, comments: 5, response: '看展局已有2人报名', responseActivityId: 'club-exhibit' },
];

export const lifePosts: LifePost[] = [
  { id: 'life-1', author: '小满', meta: '今天 · 杨浦', kind: '生活分享', text: '最近想找杨浦附近的朋友，周末一起散步或喝杯咖啡。先轻松认识，不急着定义关系。', images: [pics[0], pics[2]], tag: '#周末的一百种过法', comments: 3, resonance: 12 },
  { id: 'life-2', author: 'Mei', meta: '昨天 · 关系想法', kind: '关系话题', text: '你觉得舒服的关系，是从心动开始，还是从相处不费力开始？', images: [pics[1], pics[3]], tag: '#关系里的松弛感', comments: 12, resonance: 24 },
];
